In [2]:
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])

first three characters: oxy
last three characters: gen


In [21]:
# Slicing Strings

# 1.

print(element[:4])
print(element[4:])
print(element[:])

# 2.

print(element[-1])
print(element[-2])

# 3.
# this input starts with character "1" which is the second character of the string
# it goes up until the last character, so the string is "xyge"

print(element[1:-1])

# 4.

print(element[3:3])

# data[3:3, 4:4] would produce no output because there is no selected data for rows or columns
# data[3:3, :] would produce no output as well because no rows are selected even though all columns are selected

import numpy as np

oxyg
en
oxygen
n
e
xyge



In [18]:
data = np.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [20]:
print(data[3:3, 4:4])
print(data[3:3, :])

[]
[]


In [24]:
# Stacking Arrays

import numpy

A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

# 1.

D = A[:, :1]
E = A[:, 2:]
F = numpy.hstack([D, E])
print('F = ')
print(F)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
F = 
[[1 3]
 [4 6]
 [7 9]]


In [40]:
# Change in Inflammation

npdiff = numpy.array([ 0,  2,  5,  9, 14])

numpy.diff(npdiff)

# 1.
# it would make sense to do this on the horizontal axis 
# because it would show change in inflammation from day to day

# 2.
# if you ran the diff() on the horizontal axis, it would produce an array of (60, 39)
# because it's always one less when taking each difference

# 3.

infl_diff = numpy.diff(data, axis = 1)
max_infl_diff = numpy.max(infl_diff, axis = 1)
print("Largest Change in Inflammation for each Patient:", max_infl_diff)

Largest Change in Inflammation for each Patient: [ 7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.
  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.
  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.]
