In [1]:
3 + 5 * 4

23

In [2]:
# creating a variable and storing a value
weight_kg = 60

In [5]:
weight_kg_text = "weight in kilograms:"

In [7]:
# printing two variables in one line
print(weight_kg_text, weight_kg)

weight in kilograms: 60


In [8]:
# converting weight to pounds and printing
print('weight in pounds:', weight_kg * 2.2)

weight in pounds: 132.0


In [15]:
print(weight_kg)
weight_kg = weight_kg *3
print(weight_kg)

6210
18630


In [17]:
x = 5
y = 6
print(x + y)
x = y
print(x + y)

11
12


In [18]:
mass = 47.5
age = 122
mass = mass*5
age = age - 10
print(mass,age)

237.5 112


In [19]:
first, second = 'Grace', 'Shawn'
third, fourth = second, first
print(third,fourth)

Shawn Grace


In [21]:
import numpy

numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.]])

In [22]:
medical_data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [23]:
print(medical_data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]]


In [26]:
print(type(medical_data))
print(type(weight_kg))
print(type(weight_kg_text))

<class 'numpy.ndarray'>
<class 'int'>
<class 'str'>


In [27]:
print(medical_data.dtype)

float64


In [28]:
# rows, columns
print(medical_data.shape)

(54, 40)


In [29]:
colors = ['red', 'green', 'blue']

In [30]:
print(colors)

['red', 'green', 'blue']


In [31]:
# counts start at 0 for arrays

print('first value in medical data:', medical_data[0,0])

first value in medical data: 0.0


In [32]:
print(medical_data.shape)

(54, 40)


In [38]:
med_data_shape = medical_data.shape
print(med_data_shape[1])
middle_of_rows = int(med_data_shape[0]/2)
middle_of_cols = int(med_data_shape[1]/2)
print(middle_of_rows, middle_of_cols)

print('middle value of medical data:', medical_data[middle_of_rows, middle_of_cols])

40
27 20
middle value of medical data: 6.0


In [40]:
# slicing data

# print(medical_data[0:4, 0:10])

print(medical_data[5:10, 0:10])

[[0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]]


In [41]:
bruin = medical_data[:3, 36:]
print('bruin is:\n')
print(bruin)

bruin is:

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [42]:
import numpy as np

In [43]:
import time
print(time.ctime())

Mon Jan 27 12:21:02 2020


In [44]:
meanval, stdval = np.mean(medical_data), np.std(medical_data)

In [45]:
print('mean:',meanval,', standard deviation:', stdval)

mean: 5.658333333333333 , standard deviation: 4.352194529455482


In [46]:
maxval, minval = np.max(medical_data), np.min(medical_data)
print('max:', maxval,', min:', minval)

max: 19.0 , min: 0.0


In [50]:
patient_1 = medical_data[0,:]
print(patient_1)
len(patient_1)
print(patient_1[1])

[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]
0.0


In [51]:
max_infl_pt1 = np.max(patient_1)
print('max inflammation for patient 1:', max_infl_pt1)

max inflammation for patient 1: 18.0


In [52]:
print(np.max(medical_data, axis = 1))

[18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19.
 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19.
 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19.]


In [53]:
print(np.max(medical_data, axis = 0))

[ 0.  1.  2.  3.  3.  2.  6.  7.  8.  9. 10. 11. 10.  9.  7. 15.  7. 16.
 12. 18. 19. 14. 12. 17. 12. 12. 11.  7. 11.  8. 10.  5.  5.  7.  5.  5.
  2.  3.  1.  1.]


In [66]:
def hello_person(name="shawn", friend="tom"):
    print('Hello', name, ", and your friend", friend, "too!")

In [67]:
hello_person(friend="mike",name="barb")

Hello barb , and your friend mike too!


In [72]:
def square_numbers(x):
    return(x*x)

In [73]:
sq1 = square_numbers(5)

In [74]:
print(sq1)

25


In [76]:
5**3

def pp(base, exponent):
    return(base**exponent)

In [78]:
pp(50,3)

125000